# Site Settings
title:               "MM | Portfolio"
tagline:             "Architecture Portfolio"
description:         "A selection of built, unbuilt and research projects by Matteo Mandrile"
author:              "Matteo Mandrile"
baseurl:            ""
url:                ""
github_username:     matteomandrile
twitter_username:    matteomandrile
email:              matteo.mandrile@gmail.com

# Build settings
markdown:           kramdown
remote_theme:       LeNPaul/Millennial
paginate:           5

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Customization
sass:
  sass_dir:         assets/css
  style:            :nested

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/